[package]
name = "podatam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite="0.27.0"
chrono="0.4.23"
filetime="0.2.15"