[package]
name = "fotoalbom_vir_in_real"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite="0.27.0"
filetime = "0.2.15"  
chrono = "0.4.19"           
             